### PR TITLE
add renovatebot

### PR DESCRIPTION
**Pull request by Migelo**
As discussed in https://github.com/MisterTea/EternalTerminal/pull/622 this pull request adds the [renovatebot](https://docs.renovatebot.com/) to this repo. 

The current config will automatically merge minor updates and patches, major version bumps need to be merged manually.

### CODE REVIEW

**Comment by MisterTea** [comment]
Can you add a github action to run renovate? https://github.com/renovatebot/github-action

**Comment by Migelo** [comment]
Something that runs every 15 minutes like this? Happy to do it!

```
name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.1
        with:
          configurationFile: example/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
```

I never knew one can run renovate as an action, I've always just let it run on its own accord, what benefits do you recon this brings?

**Comment by MisterTea** [comment]
"let it run on its own accord"

What does this mean?  I assumed that without a GitHub action I would need to run some command regularly to get updates.

**Comment by Migelo** [comment]
It just triggers every so often on its own. Without a schedule I guess it runs when the load on the bot is low? After adding renovate.json you simply need to enable https://github.com/apps/renovate for this repo and that is it, no gh action needed.

**Comment by MisterTea** [comment]
Oh!  That's the part I was missing. Ok, with the GitHub hook we don't need an action.

**Comment by Migelo** [comment]
Great. Then the only thing you need to do before merging this is to add the renovate GitHub app I linked above to this repo.

**Comment by MisterTea** [comment]
Thanks!!

**Pull request merged**
