### PR TITLE
Include ninja-build and Mojave instructions

### PR DESCRIPTION
**Pull request by dgentry**
On Debian/Ubuntu, without `ninja-build`, cmake doesn't work, so added to instructions.

On Mac Mojave, `et` versions beyond 6.0.13 won't compile, so added instructions for Mojave.

### CODE REVIEW

**Comment by MisterTea** [comment]
Thanks!!

**Comment by dgentry** [comment]
OK, dumb question:  What else do I have to do to get this merged?  I figure it's the right thing to do to make `et` available on Mojave right now, and I'll work on the better fix (`filesystem`) as soon as I can in a fresh pull request.

**Comment by dgentry** [comment]
Ah, I see the other PR where you're avoiding compiling Telemetry for Mojave!  As soon as that's in, I'll take out the 6.0.13 instructions from this PR.

**Comment by dgentry** [comment]
I'm gonna close this and try again because it got weird after I fetched upstream into my fork.

**Pull request closed without merging**
