### PR TITLE
Amazon linux

### PR DESCRIPTION
**Pull request by CmdQ**
As discussed in #590, I created Dockerfiles for Amazon Linux 2023.

AL2023 builds fine, but for AL2, I get the error.

### CODE REVIEW

**Comment by MisterTea** [comment]
Thanks!  I'll take a look asap

**Comment by CmdQ** [comment]
Don't you want to include those new docker files for future troubleshooting?

**Comment by MisterTea** [comment]
I merged them into the deployment branch instead of master (with some minor changes). Thanks so much for your contribution!!

**Comment by CmdQ** [comment]
Nice to hear, you're welcome.

Thanks so much for your support, ET rocks!

**Pull request closed without merging**
