### PR TITLE
Docker container image [need help]

### PR DESCRIPTION
**Pull request by caruccio**
Hi there. I need some help figuring this out.
This is an initial docker image build for et-server, but there is something missing here.

Build it with: `cd docker && make `
Run it with: `docker run -it --rm -p 2022:2022 et-server`

The issue is this:

```
$ docker run -it --rm -p 2022:2022 et-server
+ '[' server == server ']'
+ shift
+ exec etserver --logtostdout -v 1 --cfgfile=/etc/et.cfg
[INFO 2020-02-22 21:33:43,380 etserver-main TerminalServerMain.cpp:143] In child, about to start server.
[INFO 2020-02-22 21:33:43,381 etserver-main TcpSocketHandler.cpp:202] Listening on 0.0.0.0:2022/2/1/6
[INFO 2020-02-22 21:33:43,382 etserver-main TcpSocketHandler.cpp:202] Listening on 0.0.0.0:2022/10/1/6
[INFO 2020-02-22 21:33:43,382 etserver-main TerminalServer.cpp:20] Creating server
[V1 2020-02-22 21:33:49,185 etserver-main ServerConnection.cpp:16] Accepting connection
[V1 2020-02-22 21:33:49,185 etserver-main ServerConnection.cpp:21] SERVER: got client socket fd: 8
[V1 2020-02-22 21:33:49,190 server-clientHandler SocketHandler.cpp:31] Failed a call to readAll: Broken pipe
[ERROR 2020-02-22 21:33:49,190 server-clientHandler ServerConnection.cpp:118] Error handling new client: Failed a call to readAll
[V1 2020-02-22 21:33:49,190 server-clientHandler UnixSocketHandler.cpp:161] Closing connection: 8
```

The server closes the connection. Maybe something is missing (lib or binary).

### CODE REVIEW

**Comment by MisterTea** [comment]
Is your client running 6.0.6?

**Comment by caruccio** [comment]
Sorry, forgot that.

```
[mateus@mateus et]$ docker run -it --rm  et-server --version
+ '[' server == server ']'
+ shift
+ exec etserver --logtostdout -v 1 --version
et version 6.0.6
[mateus@mateus et]$ et --version
et version 6.0.6
```

**Comment by MisterTea** [comment]
Oh!  I know what it is: we use ash to initialize the connection, so you also need to forward the ssh port

**Comment by caruccio** [comment]
Port 22 is already used by host's ssh. I can ssh to server as usual. Is there any requirement other than simply run etserver from with a container? Does it need access to

**Comment by MisterTea** [comment]
If port 22 is already used by the host, then you need to map another port (e.g. 88) to the container's 22 port. Then you need to mod your ssh_config so it can ssh to localhost and it chooses port 88

**Comment by caruccio** [comment]
Okay, there is more than I expected here.
Is there any detailed description of the internal workflow other than https://eternalterminal.dev/howitworks/?
I'm clearly missing some thing.

**Comment by MisterTea** [comment]
@caruccio maybe this will help explain: 

```
docker run -it --rm -p 2022:2022 -p 88:22 et-server
echo "Host localhost
    Port 88" >> ~/.ssh/config
et localhost
```

**Comment by caruccio** [comment]
Yeah! I got it working .There are some extra steps I was missing:

- Run sshd inside the container (was not clear from the docs)
- Map volumes /etc/ssh, /etc/passwd, /etc/shadow, /home in order to auth with same users from host

```
docker run -it --rm -p 2022:2022 -p 2222:22 \
    -v /etc/ssh:/etc/ssh \
    -v /etc/passwd:/etc/passwd \
    -v /etc/shadow:/etc/shadow \
    -v /etc/group:/etc/group \
    -v /home:/home \
    et-server
```

Thanks a lot for your help.

**Comment by caruccio** [comment]
@MisterTea I've added a README.md. Could you please validate if it's clear enough?

**Comment by MisterTea** [comment]
Great, thanks!

**Pull request merged**
