### PR TITLE
Improve macOS instructions

### PR DESCRIPTION
**Pull request by jooize**

### CODE REVIEW

**Comment by MisterTea** [comment]
How is the macports port maintained?  Can someone provide a script I can run to update the port when a new GitHub release is out?

**Comment by jooize** [comment]
```sh
port info et
```
```
et @6.0.5_1 (net)
Variants:             debug, universal

Description:          Eternal Terminal (ET) is a remote shell that automatically
                      reconnects without interrupting the session.
Homepage:             https://github.com/MisterTea/EternalTerminal

Build Dependencies:   cmake
Library Dependencies: gflags, libsodium, protobuf3-cpp
Platforms:            darwin
License:              Apache-2
Maintainers:          Email: l2dy@macports.org, GitHub: l2dy
                      Policy: openmaintainer
```

https://github.com/l2dy

Is there a way to contact @l2dy on GitHub?

**Comment by l2dy** [comment]
If you don't have a Mac, you could download `https://github.com/MisterTea/EternalTerminal/tarball/et-v6.0.5/EternalTerminal-6.0.5.tar.gz` (replace `6.0.5` with the current version), update the version in the [Portfile](https://github.com/macports/macports-ports/blob/master/net/et/Portfile) and corresponding checksums and file size.

If you have a Mac and have MacPorts installed, you can update the version in `github.setup` with `port edit et` and run `sudo port -v checksum et` to get the new checksums.

**Comment by MisterTea** [comment]
Cool, @l2dy can you add me as a maintainer so I can push new versions?

**Comment by l2dy** [comment]
You can submit a PR and add yourself as the port maintainer, but you still have to use PRs afterwards.

To get commit rights to macports/macports-ports, you should follow instructions at https://guide.macports.org/#project.membership.

**Comment by MisterTea** [comment]
@l2dy  makes sense, thanks!

**Pull request merged**
