### PR TITLE
Add codespell support (config, CI action to detect new typos) + fix some typos

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by MisterTea** [comment]
Hey, I'm not sure why we are failing the clang-format test now, but can you fix those before merging?

**Comment by yarikoptic** [comment]
I will submit later pr without changes to check if that check is green on general - https://github.com/MisterTea/EternalTerminal/actions/workflows/clang-format-check.yml shows that last time it was ran was 2 months ago, so may be just some new version of tooling causes it now to fail, not that changes in this pr

**Comment by KapJI** [comment]
Clang-format is right here, extra letter made `{`s in that block unalighned. I guess you need to add an extra space for those line.

**Comment by yarikoptic** [comment]
thanks, pushed results of `clang-format -i src/terminal/TelemetryService.cpp` -- let's see how it feels now!

**Comment by MisterTea** [comment]
Thanks!

**Pull request merged**
